<a href="https://colab.research.google.com/github/vurachaitanya/API-pi/blob/master/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
* Declaring Arrays using Numpy
* Statistical Analysis Using Numpy
* manipulation of array
* linear Algebra using Numpy

if we add below two objects we get added to the array not adding each

In [1]:
a = [1,2,9] # List can't do mathamatical caliculations where Arrays can be done
b = [7,2,6]
c = a+b
print(c)

[1, 2, 9, 7, 2, 6]


In [2]:
import numpy

a = [1,2,9]
b = [7,2,6]
c = a+b
print (c)

a=numpy.array([2,4,6])
b=numpy.array([7,1,8])
c=a+b
print (c)

[1, 2, 9, 7, 2, 6]
[ 9  5 14]


# Declaring Arrays using Numpy

In [17]:
#x=numpy.array([4,5,6])
x=numpy.array([[7,4,2],[1,5,9],[3,6,7]])
print(x)
print(x.size) # total number of elements in the array

print(x.shape) # shape of array --> rows & Cols

print(x[1,2]) # Prints the 9 from 2nd column(0,1) 3rd row (0,1,2)
print (x[2,1]) # prints 3rd column 2nd row object
print(x[2,0:3]) ## below all are similar
print (x[2,:])
print (x[2])
# Columns 2nd
print ("                          ")
print(x[:,2])
print ("                          ")
x[:,1]=[7,8,9] ## Replace 2nd column 
print(x)
print ("                          ")
# Add 0th column + 1st Column and store result in 2nd column
x[:,2]=x[:,0]+x[:,1]
print(x)
print ("                          ")

[[7 4 2]
 [1 5 9]
 [3 6 7]]
9
(3, 3)
9
6
[3 6 7]
[3 6 7]
[3 6 7]
                          
[2 9 7]
                          
[[7 7 2]
 [1 8 9]
 [3 9 7]]
                          
[[ 7  7 14]
 [ 1  8  9]
 [ 3  9 12]]
                          


In [26]:
x=numpy.ones(5) # arrays with values as 1
print(x)
print ("                          ")
y=numpy.ones((2,5))
print(y)

print ("                          ")
print ("                          ")
z=numpy.zeros((4,6))
print(z)
print ("                          ")
print ("                          ")
c=numpy.array([[1,2,3],[2,4],[1,5,7,9]])
print(c)
c[2][3]

[1. 1. 1. 1. 1.]
                          
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
                          
                          
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
                          
                          
[list([1, 2, 3]) list([2, 4]) list([1, 5, 7, 9])]


9

In [27]:
x=2*numpy.ones((2,4))
print(x)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [28]:
x=numpy.arange(10) # sequential array
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
x=numpy.arange(3,12)
print(x)

[ 3  4  5  6  7  8  9 10 11]


In [31]:
x=numpy.arange(3,12,2) # every 2nd number should be removed
print(x)

[ 3  5  7  9 11]


In [32]:
x=numpy.linspace(start=4,stop=6,num=4) # Need 4 values starting from 4 to 6
print(x)

[4.         4.66666667 5.33333333 6.        ]


In [34]:
x=numpy.linspace(1,9,12) # 12 objects
print(x)
type(x)
x.dtype

[1.         1.72727273 2.45454545 3.18181818 3.90909091 4.63636364
 5.36363636 6.09090909 6.81818182 7.54545455 8.27272727 9.        ]


dtype('float64')

In [41]:
x=numpy.logspace(0,4,5) # Log spaces 1.e+4 = 1*10power of 4
y=y.astype('int32')
print(x)
print(y)
print(numpy.log10(10),numpy.log10(1000))

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[    1    10   100  1000 10000]
1.0 3.0


In [42]:
x=numpy.logspace(0,4,5,dtype='int32')
print(x)

[    1    10   100  1000 10000]


# Statistical Anaysis using Numpy


In [46]:
x=numpy.array([[7,4,5],[4,8,1],[4,2,7]])
print(x)
print(x.min())
print(x.max())
print(x.mean())


[[7 4 5]
 [4 8 1]
 [4 2 7]]
1
8
4.666666666666667


In [49]:
x=numpy.array([[7,4,5],[4,8,1],[4,2,7]])
print(x)
print(x.min(axis=0) )# axis=0 is for column wise operation
x.max(axis=0)
print("                      ")
print (x.min(axis=1)) # Axis=1 for row wise operation

print("                      ")
print("                      ")
x.max(axis=1)
x.mean(axis=1)

[[7 4 5]
 [4 8 1]
 [4 2 7]]
[4 2 1]
                      
[4 1 2]
                      
                      


array([5.33333333, 4.33333333, 4.33333333])

# Spread of temperature is spread across delhi but mumbai its more nearer to mean
[link text](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi1.wp.com%2Fstatisticsbyjim.com%2Fwp-content%2Fuploads%2F2018%2F02%2Fvariability.png%3Fresize%3D576%252C384&imgrefurl=https%3A%2F%2Fstatisticsbyjim.com%2Fbasics%2Fvariability-range-interquartile-variance-standard-deviation%2F&tbnid=2Kfr-e5-kf1N3M&vet=12ahUKEwicx76Q1IjoAhXCLisKHU32DEAQMygBegUIARCAAg..i&docid=h9zgcP9jrIw1QM&w=576&h=384&q=variance%20graph&ved=2ahUKEwicx76Q1IjoAhXCLisKHU32DEAQMygBegUIARCAAg)

![alt text](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi1.wp.com%2Fstatisticsbyjim.com%2Fwp-content%2Fuploads%2F2018%2F02%2Fvariability.png%3Fresize%3D576%252C384&imgrefurl=https%3A%2F%2Fstatisticsbyjim.com%2Fbasics%2Fvariability-range-interquartile-variance-standard-deviation%2F&tbnid=2Kfr-e5-kf1N3M&vet=12ahUKEwicx76Q1IjoAhXCLisKHU32DEAQMygBegUIARCAAg..i&docid=h9zgcP9jrIw1QM&w=576&h=384&q=variance%20graph&ved=2ahUKEwicx76Q1IjoAhXCLisKHU32DEAQMygBegUIARCAAg)


In [56]:
# Variance = Spread of the data across mean
# Teamp of delhi & mumbai
d=numpy.array([19,20,24,26,29,31,36,44,49,55,35,25])
m=numpy.array([21,22,22,33,33,22,33,33,22,22,33])
print(  d.mean() )
print( m.mean() )
print(numpy.var(d))  
print(numpy.var(m))        

32.75
26.90909090909091
121.02083333333333
30.99173553719009


# Bank example
* if customer variant is very small then age is not affecting the customer of bank who are leaving.
* So Variance is been used where the spread of the data is been viewed where mean and median is more of a mathamatical caluculations 
# Image examples
* if the pixcels variant is more then some object is present in that image
* if the variant is less or zero the images dose not have any object or it could be black or blank
* Android phone if take blank image or black image it would share us to delete by using the variant of the image. it caliculates black(255,255,255), red(255,0,255) etc

# Variant if more need to consider and if less don't


# Standard deviation = square root of variance

In [57]:
print(numpy.std(d))
print(numpy.std(m))

11.000946928939042
5.567022142689042


# Manipulation of arrays


In [0]:
d=numpy.array([19,20,24,26,29,31,36,44,49,55,35,25])
m=numpy.array([21,22,22,33,33,22,33,33,22,22,33])
d.size
d=d.reshape(6,3)
print(d)
d.shape
d.dtype
d=d.astype('float32')
d

# Linear algebra using Numpy

In [61]:
m=numpy.matrix([[4,5,6],[6,3,6],[8,2,9]]) #Matrix should have all columes and rows 3x3 and all the values should be present
print(numpy.linalg.inv(m))
print(numpy.linalg.inv(m)*m)

print(" Rank of matrix")
print(numpy.linalg.matrix_rank(m))
print ("eigen Vectors")
print(numpy.linalg.eig(m))

[[-0.35714286  0.78571429 -0.28571429]
 [ 0.14285714  0.28571429 -0.28571429]
 [ 0.28571429 -0.76190476  0.42857143]]
[[ 1.00000000e+00  1.11022302e-16  7.77156117e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00 -1.11022302e-16  1.00000000e+00]]
 Rank of matrix
3
eigen Vectors
(array([16.74596669, -2.        ,  1.25403331]), matrix([[-0.52223297, -0.79075654, -0.52223297],
        [-0.52223297,  0.33101437, -0.52223297],
        [-0.67419986,  0.51491124,  0.67419986]]))


In [62]:
#2x+3y=13
#4x-y=5
a=[[2,3],[4,-1]]
b=[13,5]
numpy.linalg.solve(a,b)

array([2., 3.])